# Dependabot configuration for automatic dependency updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # NPM dependencies (TypeScript, build tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group all non-major updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Rust/Cargo dependencies (WASM)
  - package-ecosystem: "cargo"
    directory: "/wasm"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group all non-major updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
